#!/usr/bin/env python3
r"""Aura Design System — generator.

Reads the single source of truth (``aura-tokens.json``) and emits every
downstream consumer into ``dist/``:

    dist/aura.py            the apps' vendored theme module (33 apps share it)
    dist/AuraDark.colors    KDE/Plasma color-scheme  (dark mode)
    dist/AuraLight.colors   KDE/Plasma color-scheme  (light mode)
    dist/aura.css           CSS custom properties for the web (light + dark)
    dist/aura-swatches.html self-contained visual reference of every token

One language, three consumers — Plasma shell, desktop apps, and the web — all
derived from the same tokens.  Change a token in ``aura-tokens.json`` and run::

    python3 generate.py

The command is idempotent: it fully regenerates ``dist/`` from the tokens and
the ``aura.template.py`` (which holds aura.py's logic with the palette/accent
punched out as markers).  Nothing here hardcodes a colour beyond what the
tokens define.
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TOKENS_PATH = os.path.join(HERE, "aura-tokens.json")
TEMPLATE_PATH = os.path.join(HERE, "aura.template.py")
DIST = os.path.join(HERE, "dist")

# Palette keys the apps' aura.py TOKENS dark/light dicts carry, in display
# order.  (accent / on-accent are derived at runtime by aura._resolve, so they
# are intentionally NOT part of these base dicts.)
PALETTE_KEYS = [
    "bg", "bg2", "surface", "surface2", "surface3",
    "border", "border2", "text", "muted", "faint", "field",
    "ok", "warn", "danger",
]

# Grouping for the emitted aura.py dict lines (mirrors the original layout).
_AURA_GROUPS = [
    ["bg", "bg2", "surface"],
    ["surface2", "surface3"],
    ["border", "border2"],
    ["text", "muted", "faint"],
    ["field"],
    ["ok", "warn", "danger"],
]


def load_tokens():
    with open(TOKENS_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# small color helpers (self-contained; mirror aura.py's mix())
# ---------------------------------------------------------------------------

def _rgb(c):
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_str(c):
    return ",".join(str(v) for v in _rgb(c))


def _hex(rgb):
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(round(v)))) for v in rgb)


def _mix(a, b, t):
    ra, rb = _rgb(a), _rgb(b)
    return _hex(tuple(ra[i] + (rb[i] - ra[i]) * t for i in range(3)))


# ---------------------------------------------------------------------------
# (a) aura.py  — fill the template markers from the tokens
# ---------------------------------------------------------------------------

def _dict_lines(mode_tokens):
    """Render the grouped ``"key": "#hex",`` lines for one mode."""
    out = []
    for group in _AURA_GROUPS:
        parts = ['"%s": "%s"' % (k, mode_tokens[k]) for k in group]
        out.append("        " + ", ".join(parts) + ",")
    return "\n".join(out)


def gen_aura_py(tokens):
    tpl = open(TEMPLATE_PATH, encoding="utf-8").read()
    accent = tokens["brand"]["accent"]
    dark_lines = _dict_lines(tokens["modes"]["dark"])
    light_lines = _dict_lines(tokens["modes"]["light"])
    default_accent = (
        'DEFAULT_ACCENT = "%s"          # Aura brand accent (both modes, v%s)'
        % (accent, tokens["$version"])
    )
    out = tpl
    out = out.replace("        # %%AURA_TOKENS_DARK%%", dark_lines)
    out = out.replace("        # %%AURA_TOKENS_LIGHT%%", light_lines)
    out = out.replace("# %%AURA_DEFAULT_ACCENT%%", default_accent)
    # header note so the generated file is obviously generated
    banner = (
        '# NOTE: this file is GENERATED by branding/aura-design-system/'
        'generate.py\n#       from aura-tokens.json (v%s). Do not edit by hand;'
        ' edit the\n#       tokens and re-run the generator.\n'
        % tokens["$version"]
    )
    out = out.replace("from __future__ import annotations\n",
                      "from __future__ import annotations\n\n" + banner, 1)
    if "%%AURA" in out:
        raise SystemExit("aura.py: unfilled marker remains")
    return out


# ---------------------------------------------------------------------------
# (b) Plasma / KDE color-schemes
# ---------------------------------------------------------------------------

def _color_effects():
    # Standard, conservative disabled/inactive effects (Plasma defaults shape).
    return (
        "[ColorEffects:Disabled]\n"
        "ChangeSelectionColor=true\n"
        "Color=56,62,74\n"
        "ColorAmount=0\n"
        "ColorEffect=0\n"
        "ContrastAmount=0.65\n"
        "ContrastEffect=1\n"
        "IntensityAmount=0.1\n"
        "IntensityEffect=2\n\n"
        "[ColorEffects:Inactive]\n"
        "ChangeSelectionColor=true\n"
        "Color=112,125,138\n"
        "ColorAmount=0.025\n"
        "ColorEffect=2\n"
        "ContrastAmount=0.1\n"
        "ContrastEffect=2\n"
        "IntensityAmount=0\n"
        "IntensityEffect=0\n\n"
    )


def gen_plasma(tokens, mode):
    m = tokens["modes"][mode]
    accent = m["accent"]
    ok, warn, danger = m["ok"], m["warn"], m["danger"]
    info = tokens["semantic"]["info"]
    name = "Aura %s" % ("Dark" if mode == "dark" else "Light")

    def rows(bg, alt, fg, fg_inactive):
        return (
            "BackgroundNormal=%s\n" % _rgb_str(bg)
            + "BackgroundAlternate=%s\n" % _rgb_str(alt)
            + "ForegroundNormal=%s\n" % _rgb_str(fg)
            + "ForegroundInactive=%s\n" % _rgb_str(fg_inactive)
            + "ForegroundActive=%s\n" % _rgb_str(accent)
            + "ForegroundLink=%s\n" % _rgb_str(accent)
            + "ForegroundVisited=%s\n" % _rgb_str(tokens["brand"]["accent-strong"])
            + "ForegroundNegative=%s\n" % _rgb_str(danger)
            + "ForegroundNeutral=%s\n" % _rgb_str(warn)
            + "ForegroundPositive=%s\n" % _rgb_str(ok)
            + "DecorationFocus=%s\n" % _rgb_str(accent)
            + "DecorationHover=%s\n" % _rgb_str(accent)
        )

    out = []
    out.append("[General]\n"
               "ColorScheme=%s\n" % name.replace(" ", "")
               + "Name=%s\n" % name
               + "shadeSortColumn=true\n\n")
    out.append("[Colors:Window]\n" + rows(m["bg"], m["bg2"], m["text"], m["muted"]) + "\n")
    out.append("[Colors:View]\n" + rows(m["surface"], m["surface2"], m["text"], m["muted"]) + "\n")
    out.append("[Colors:Button]\n" + rows(m["surface2"], m["surface3"], m["text"], m["muted"]) + "\n")
    # Selection: accent ground, on-accent text.
    out.append("[Colors:Selection]\n" + rows(accent, accent, m["on-accent"], _mix(accent, m["on-accent"], 0.35)) + "\n")
    out.append("[Colors:Tooltip]\n" + rows(m["surface2"], m["surface3"], m["text"], m["muted"]) + "\n")
    out.append("[Colors:Complementary]\n" + rows(m["bg2"], m["surface"], m["text"], m["muted"]) + "\n")
    out.append("[Colors:Header]\n" + rows(m["surface"], m["surface2"], m["text"], m["muted"]) + "\n")
    out.append(_color_effects())
    out.append("[WM]\n"
               + "activeBackground=%s\n" % _rgb_str(m["bg2"])
               + "activeForeground=%s\n" % _rgb_str(m["text"])
               + "activeBlend=%s\n" % _rgb_str(m["text"])
               + "inactiveBackground=%s\n" % _rgb_str(m["bg"])
               + "inactiveForeground=%s\n" % _rgb_str(m["muted"])
               + "inactiveBlend=%s\n" % _rgb_str(m["muted"])
               + "\n")
    out.append("[KDE]\n"
               "contrast=4\n"
               "widgetStyle=Breeze\n\n")
    header = (";  %s — generated by aura-design-system/generate.py from "
              "aura-tokens.json v%s\n;  accent %s -> DecorationFocus/Hover + "
              "Selection background\n\n"
              % (name, tokens["$version"], accent))
    return header + "".join(out)


# ---------------------------------------------------------------------------
# (c) CSS custom properties for the web
# ---------------------------------------------------------------------------

def _mode_vars(m, indent="  "):
    lines = []
    for k in PALETTE_KEYS:
        lines.append("%s--aura-%s: %s;" % (indent, k, m[k]))
    lines.append("%s--aura-accent: %s;" % (indent, m["accent"]))
    lines.append("%s--aura-on-accent: %s;" % (indent, m["on-accent"]))
    return "\n".join(lines)


def gen_css(tokens):
    b = tokens["brand"]
    light = tokens["modes"]["light"]
    dark = tokens["modes"]["dark"]
    sem = tokens["semantic"]
    parts = []
    parts.append("/*\n * Aura Design System — CSS custom properties.\n"
                 " * GENERATED by aura-design-system/generate.py from "
                 "aura-tokens.json v%s.\n"
                 " * Consumed by the web (quickopen.ai + artifacts). Light is "
                 "the :root default;\n * dark applies via prefers-color-scheme "
                 "and an explicit [data-theme] override.\n */\n" % tokens["$version"])

    # brand + non-mode tokens live on :root unconditionally
    brand_lines = [
        "  --aura-brand-accent: %s;" % b["accent"],
        "  --aura-brand-accent-strong: %s;" % b["accent-strong"],
        "  --aura-brand-accent-edge: %s;" % b["accent-edge"],
        "  --aura-beam: %s;" % b["beam"],
    ]
    for k, v in tokens["radius"].items():
        brand_lines.append("  --aura-radius-%s: %s;" % (k, v))
    for k, v in tokens["space"].items():
        brand_lines.append("  --aura-space-%s: %s;" % (k, v))
    brand_lines.append("  --aura-font-ui: %s;" % tokens["type"]["family-ui"])
    brand_lines.append("  --aura-font-mono: %s;" % tokens["type"]["family-mono"])
    for k, v in tokens["type"]["scale"].items():
        brand_lines.append("  --aura-text-%s: %s;" % (k, v))
    for k, v in tokens["type"]["weight"].items():
        brand_lines.append("  --aura-weight-%s: %s;" % (k, v))
    for k, v in tokens["elevation"].items():
        brand_lines.append("  --aura-elevation-%s: %s;" % (k, v))
    for k, v in sem.items():
        brand_lines.append("  --aura-%s: %s;" % (k, v))

    parts.append(":root {\n"
                 + "\n".join(brand_lines) + "\n\n"
                 + "  /* light mode (default) */\n"
                 + _mode_vars(light) + "\n"
                 + "  color-scheme: light dark;\n}\n")

    parts.append("@media (prefers-color-scheme: dark) {\n"
                 "  :root:not([data-theme=\"light\"]) {\n"
                 + _mode_vars(dark, indent="    ") + "\n  }\n}\n")

    parts.append(":root[data-theme=\"dark\"] {\n"
                 + _mode_vars(dark) + "\n}\n")
    parts.append(":root[data-theme=\"light\"] {\n"
                 + _mode_vars(light) + "\n}\n")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# (d) swatch reference page
# ---------------------------------------------------------------------------

def _swatch_grid(tokens, mode):
    m = tokens["modes"][mode]
    cells = []
    ordered = PALETTE_KEYS + ["accent", "on-accent"]
    for k in ordered:
        v = m[k]
        txt = m["text"] if k not in ("text", "on-accent") else (
            m["bg"] if k == "text" else m["accent"])
        cells.append(
            '<div class="sw"><div class="chip" style="background:%s;'
            'border-color:%s"></div><div class="lab"><b>%s</b>'
            '<code>%s</code></div></div>' % (v, m["border2"], k, v))
    return "\n".join(cells)


def gen_swatches(tokens):
    dark = tokens["modes"]["dark"]
    light = tokens["modes"]["light"]

    def panel(mode, m):
        return (
            '<section class="panel %s" style="background:%s;color:%s;'
            'border-color:%s">\n'
            '<h2 style="color:%s">Aura %s</h2>\n'
            '<div class="grid">\n%s\n</div>\n'
            '<h3 style="color:%s">brand / semantic</h3>\n'
            '<div class="grid">%s</div>\n</section>'
            % (mode, m["bg"], m["text"], m["border"], m["text"],
               "Dark" if mode == "dark" else "Light",
               _swatch_grid(tokens, mode), m["muted"],
               _brand_swatches(tokens, m)))

    style = (
        "body{margin:0;font-family:%s;background:#0b0d11;padding:24px;}"
        ".wrap{display:grid;grid-template-columns:1fr 1fr;gap:20px;"
        "max-width:1200px;margin:0 auto;}"
        "@media(max-width:820px){.wrap{grid-template-columns:1fr;}}"
        ".panel{border:1px solid;border-radius:16px;padding:20px;}"
        ".panel h1,.panel h2{margin:.2em 0 .6em;font-size:20px;}"
        ".panel h3{margin:1.2em 0 .5em;font-size:12px;text-transform:uppercase;"
        "letter-spacing:.08em;}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));"
        "gap:10px;}"
        ".sw{display:flex;gap:10px;align-items:center;}"
        ".chip{width:34px;height:34px;border-radius:8px;border:1px solid;flex:0 0 auto;}"
        ".lab{display:flex;flex-direction:column;font-size:12px;line-height:1.3;}"
        ".lab code{opacity:.75;font-size:11px;}"
        "h1.title{color:#f1f3f7;text-align:center;font-family:%s;font-weight:800;}"
        "p.sub{color:#9aa4b2;text-align:center;margin-top:-6px;}"
        % (tokens["type"]["family-ui"], tokens["type"]["family-ui"]))

    return (
        "<!doctype html><html><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>Aura Design System — Swatches</title><style>%s</style></head>"
        "<body><h1 class=\"title\">Aura Design System</h1>"
        "<p class=\"sub\">tokens v%s · accent %s · every token, both modes</p>"
        "<div class=\"wrap\">%s\n%s</div></body></html>"
        % (style, tokens["$version"], tokens["brand"]["accent"],
           panel("dark", dark), panel("light", light)))


def _brand_swatches(tokens, m):
    b = tokens["brand"]
    sem = tokens["semantic"]
    items = list(b.items()) + list(sem.items())
    cells = []
    for k, v in items:
        cells.append(
            '<div class="sw"><div class="chip" style="background:%s;'
            'border-color:%s"></div><div class="lab"><b>%s</b>'
            '<code>%s</code></div></div>' % (v, m["border2"], k, v))
    return "\n".join(cells)


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

def _write(rel, content):
    path = os.path.join(DIST, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("  emit %-22s %6d bytes" % (rel, len(content)))
    return path


def main():
    tokens = load_tokens()
    os.makedirs(DIST, exist_ok=True)
    print("Aura DS generate — tokens v%s, accent %s"
          % (tokens["$version"], tokens["brand"]["accent"]))
    _write("aura.py", gen_aura_py(tokens))
    _write("AuraDark.colors", gen_plasma(tokens, "dark"))
    _write("AuraLight.colors", gen_plasma(tokens, "light"))
    _write("aura.css", gen_css(tokens))
    _write("aura-swatches.html", gen_swatches(tokens))
    print("done -> %s" % DIST)


if __name__ == "__main__":
    main()
